import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { LanguageProvider } from "./languagecontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "krishyani agro ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <LanguageProvider>

        <Header />
        <main>
          {children}
        </main>
        </LanguageProvider>

      </body>
    </html>
  );
}

