import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { LanguageProvider } from "./languagecontext";
import Footer from "@/components/footer";
import { GlobalStateProvider } from "@/components/GlobalState";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "krishyani agro ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/images/website_logobg.png" />
      </Head>
      <body className={inter.className}>
        <GlobalStateProvider>
          <LanguageProvider>
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </LanguageProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}

